### ISSUE TITLE
Small packaging nitpick: don't need setup.cfg at all

### ISSUE THREAD

**Issue by psobolewskiPhD** [TheJacksonLaboratory/activelearning#1]
The setup.cfg only has a url, which can go in pyproject.toml under:
`[project.urls]`
See: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#urls

For the current behavior (Homepage on pypi)
you would use:
`Homepage = "https://github.com/TheJacksonLaboratory/activelearning"`

But you can have multiple entries, like "Source code" vs Homepage

**Comment by fercer** [comment]
Thanks for your contribution @psobolewskiPhD!

That change was added in #5.
