### ISSUE TITLE
Nitpick #2: you shouldn't need `wheel` in build requirements

### ISSUE THREAD

**Issue by psobolewskiPhD** [TheJacksonLaboratory/activelearning#2]
With setuptools >42 wheel should be injected when needed according to pep517
https://github.com/TheJacksonLaboratory/activelearning/blob/d35b2a376278f589703f5986692d029bfa9e8a68/pyproject.toml#L55

**Comment by psobolewskiPhD** [comment]
That looks like something outdated in the cookie cutter!

**Comment by fercer** [comment]
The dependencies list in pyproject.toml was updated to remove "weel" in #5. 
Thanks again @psobolewskiPhD for your comments!
