### ISSUE TITLE
Missing dependencies in pyproject.toml

### ISSUE THREAD

**Issue by psobolewskiPhD** [TheJacksonLaboratory/activelearning#3]
For converting to a conda package down the line, the dependencies must be properly specified.

At quick glance I see imports from napari, so that should be listed.
Also I see an import from dask.array, so listing `dask[array]` and zarr.

(these are obviously dependencies of dependencies, but should be made explicit in pyproject.toml if they are directly imported)

**Comment by fercer** [comment]
Thanks for your recommendation @psobolewskiPhD!

Certainly, the idea is to convert it into a conda package in the near future, so it is helpful to reduce the requirements down the line.

The list of dependencies was updated in #5. I'll continue checking for dependencies that are still missing in pyproject.toml later.
