### ISSUE TITLE
cellpose-napari optional dependency

### ISSUE THREAD

**Issue by psobolewskiPhD** [TheJacksonLaboratory/activelearning#6]
Related to dependencies:
https://github.com/TheJacksonLaboratory/activelearning/blob/6543033b2669d143e08fc9bb27a99e7de7652695/pyproject.toml#L39-L42

cellpose-napari is unmaintained at doesn't run currently
I think if you want to still have it, you need to also pin cellpose upper bound like `<3` perhaps?

An alternative could be:
https://github.com/guiwitz/napari-serialcellpose
This works for me at present and Guillaume has been very responsive in the past.

**Comment by fercer** [comment]
Thanks for noticing that the cellpose plugin is not maintained @psobolewskiPhD!

I changed the optional dependency to require directly `cellpose'>3.0.0,<=3.0.10'` in PR #7. That version of cellpose has the `train` module exposed, which is needed for fine tuning.
